# DB
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = demo
quarkus.datasource.password = demo
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/demo
quarkus.datasource.jdbc.max-size=8
quarkus.datasource.jdbc.min-size=2
quarkus.hibernate-orm.database.generation=drop-and-create
# Service
quarkus.application.name=QuarkusVeggieService
quarkus.package.jar.type=uber-jar

#Rest client
quarkus.rest-client."superhero-api".url=http://localhost:8081

#OTel
quarkus.otel.metrics.enabled=true
quarkus.otel.logs.enabled=true
quarkus.otel.azure.applicationinsights.connection.string=InstrumentationKey=00000000-0000-0000-0000-000000000000
quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n
quarkus.datasource.jdbc.telemetry=true
quarkus.otel.metrics.enabled=true
