services:
  db:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=demo
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 2s
      retries: 5

  superhero:
    image: nativetelemetry.azurecr.io/quarkus-native-monitoring:82ea9e2cc21802e83ac94b665dbd2ce4307458d7
    ports:
      - 8081:8081
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/demo
      - QUARKUS_DATASOURCE_USERNAME=demo
      - QUARKUS_DATASOURCE_PASSWORD=demo
      - QUARKUS_OTEL_AZURE_APPLICATIONINSIGHTS=InstrumentationKey=00000000-0000-0000-0000-000000000000
    command:
      |
      /bin/bash -c "./application -Dquarkus.http.host=0.0.0.0 -Dquarkus.debug.print-startup-times=true"
    depends_on:
      db:
        condition: service_healthy
