name: Update workshop template
on:
  push:
    branches:
      - base

jobs:
  update_template:
    name: Update template
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update template
        run: |
          git config --global user.name "ci-rebot"
          git config --global user.email "cirebot.github@gmail.com"
          ./scripts/repo/create-github-template.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
