name: Trigger auto deployment for veggie-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ add-monitoring ]
    paths:
    - 'code/spring-boot-telemetry/**'
    - '.github/workflows/veggie-service-AutoDeployTrigger-e5d2717e-8b14-44fa-bfb8-5a9fdd293f8b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.VEGGIESERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.VEGGIESERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.VEGGIESERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/code/spring-boot-telemetry 
          registryUrl: nativeregistry.azurecr.io
          registryUsername: ${{ secrets.VEGGIESERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.VEGGIESERVICE_REGISTRY_PASSWORD }}
          containerAppName: veggie-service
          resourceGroup: native-telemetry
          imageToBuild: nativeregistry.azurecr.io/veggie-service:${{ github.sha }}
          environmentVariables: 'SPRING_DATASOURCE_URL=${{ secrets.DATABASE_URL }} SPRING_DATASOURCE_USERNAME=${{ secrets.DATABASE_USERNAME }} SPRING_DATASOURCE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} APPLICATIONINSIGHTS_CONNECTION_STRING=${{ secrets.APPLICATIONINSIGHTS_CONNECTION_STRING }} CLIENT_SUPERHERO_URL=${{ secrets.CLIENT_SUPERHERO_URL }}'
          _buildArgumentsKey_: |
            _buildArgumentsValues_


